name: Node.js React CI/CD

on:
  push:
    branches: [ MVP, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Test Backend
      run: |
        cd backend
        npm ci
        npm test --if-present

    - name: Test Frontend
      run: |
        cd frontend
        npm ci
        npm test --if-present
